In [7]:

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score, f1_score
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import warnings
import tensorflow as tf
import os
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator
from keras.models import load_model
from sklearn.metrics import classification_report
from random import shuffle

C:\Users\nataw\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [8]:
def load_images_from_folder():
    img_size = 224
    images = []
    image_paths = 'E:/Drowsiness/Data_CNN/train/alert/'
    for filename in os.listdir(image_paths):
        img = cv2.imread(os.path.join(image_paths,filename))
        if img is not None:
            img = cv2.resize(img,(img_size,img_size))
            images.append([np.array(img),[1,0]])
    
    image_paths = 'E:/Drowsiness/Data_CNN/train/drowsy/'
    for filename in os.listdir(image_paths):
        img = cv2.imread(os.path.join(image_paths,filename))
        if img is not None:
            img = cv2.resize(img,(img_size,img_size))
            images.append([np.array(img),[0,1]])
    shuffle(images)
    return images

In [9]:
def load_images_from_folder_test():
    img_size = 224
    images = []
    image_paths = 'E:/Drowsiness/Data_CNN/test/alert/'
    for filename in os.listdir(image_paths):
        img = cv2.imread(os.path.join(image_paths,filename))
        if img is not None:
            img = cv2.resize(img,(img_size,img_size))
            images.append([np.array(img),[1,0]])
    
    image_paths = 'E:/Drowsiness/Data_CNN/test/drowsy/'
    for filename in os.listdir(image_paths):
        img = cv2.imread(os.path.join(image_paths,filename))
        if img is not None:
            img = cv2.resize(img,(img_size,img_size))
            images.append([np.array(img),[0,1]])
    shuffle(images)
    return images

In [10]:
train = load_images_from_folder()

In [11]:
train = np.array(train)

In [12]:
train.shape

(4851, 2)

In [13]:
X_train = np.array([i[0] for i in train]).reshape(-1,224,224,3)/255.

In [14]:
y_train = np.array([i[1] for i in train])

In [15]:
train = 0

In [16]:
X_train[0]

array([[[0.09803922, 0.38431373, 0.4627451 ],
        [0.09803922, 0.38431373, 0.4627451 ],
        [0.09411765, 0.38039216, 0.45882353],
        ...,
        [0.07843137, 0.12941176, 0.19215686],
        [0.07843137, 0.12941176, 0.19215686],
        [0.07843137, 0.12941176, 0.19215686]],

       [[0.09803922, 0.38431373, 0.46666667],
        [0.09803922, 0.38431373, 0.4627451 ],
        [0.09803922, 0.38431373, 0.4627451 ],
        ...,
        [0.0745098 , 0.1254902 , 0.18823529],
        [0.0745098 , 0.1254902 , 0.18823529],
        [0.0745098 , 0.1254902 , 0.18823529]],

       [[0.10588235, 0.39215686, 0.47058824],
        [0.10588235, 0.39215686, 0.46666667],
        [0.10196078, 0.38823529, 0.46666667],
        ...,
        [0.06666667, 0.11764706, 0.18039216],
        [0.06666667, 0.11764706, 0.18039216],
        [0.06666667, 0.11764706, 0.18039216]],

       ...,

       [[0.16862745, 0.25098039, 0.25490196],
        [0.16470588, 0.24705882, 0.25098039],
        [0.15686275, 0

In [17]:
y_train

array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [0, 1],
       [0, 1],
       [1, 0]])

In [18]:
datagen = ImageDataGenerator(rotation_range=30,width_shift_range=0.2)
datagen.fit(X_train)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [14]:
from keras import backend
from keras.models import Sequential
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.layers.core import Dense, Flatten,Activation,Dropout
model = Sequential()
# Layer 1: Convolutional Layer
model.add(Conv2D(filters=32, kernel_size=(3,3), input_shape=(224,224,3), activation='relu',))
# Layer 2: Pooling Layer
model.add(MaxPooling2D(pool_size=(3,3)))
# Layer 3: Convolutional Layer
model.add(Conv2D(filters=32, kernel_size=(3,3), input_shape=(224,224,3), activation='relu',))
# Layer 4: Pooling Layer
model.add(MaxPooling2D(pool_size=(3,3)))
# Layer 5: Flatten Layer
model.add(Conv2D(filters=64, kernel_size=(3,3), input_shape=(224,224,3), activation='relu',))

model.add(MaxPooling2D(pool_size=(3,3)))

model.add(Flatten())
# Layer 6: Dense Layer (Hidden Layer)
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
# Layer 7: Dense Layer (Output Layer)
model.add(Dense(2, activation='softmax'))

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 222, 222, 32)      896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 72, 72, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 24, 24, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 22, 22, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3136)             

In [16]:
model.compile(optimizer="adam",loss='categorical_crossentropy',metrics=['accuracy'])

In [17]:
tf.debugging.set_log_device_placement(True)
model.fit_generator(datagen.flow(X_train, y_train, batch_size=32),
                    validation_data=(X_test,y_test),
                    steps_per_epoch=len(X_train) / 32, epochs=50)


Epoch 1/50
122/121 [==============================] - 36s 294ms/step - loss: 0.6670 - accuracy: 0.6137 - val_loss: 0.7706 - val_accuracy: 0.6303
Epoch 2/50
122/121 [==============================] - 34s 275ms/step - loss: 0.6482 - accuracy: 0.6369 - val_loss: 0.6269 - val_accuracy: 0.6643
Epoch 3/50
122/121 [==============================] - 34s 275ms/step - loss: 0.6174 - accuracy: 0.6577 - val_loss: 0.6070 - val_accuracy: 0.6807
Epoch 4/50
122/121 [==============================] - 34s 277ms/step - loss: 0.6068 - accuracy: 0.6696 - val_loss: 0.6160 - val_accuracy: 0.6488
Epoch 5/50
122/121 [==============================] - 34s 276ms/step - loss: 0.5937 - accuracy: 0.6778 - val_loss: 0.5733 - val_accuracy: 0.7116
Epoch 6/50
122/121 [==============================] - 34s 278ms/step - loss: 0.5756 - accuracy: 0.6985 - val_loss: 0.5472 - val_accuracy: 0.7291
Epoch 7/50
122/121 [==============================] - 34s 276ms/step - loss: 0.5603 - accuracy: 0.7031 - val_loss: 0.5558 - val_a

In [18]:
model.save('CNN_Model.h5')

<h1>Train เพิ่มอีก  epochs=50<h1>

In [19]:
model = load_model('CNN_Model.h5')
tf.debugging.set_log_device_placement(True)
model.fit_generator(datagen.flow(X_train, y_train, batch_size=32),
                    validation_data=(X_test,y_test),
                    steps_per_epoch=len(X_train) / 32, epochs=50)

Epoch 1/50
122/121 [==============================] - 93s 761ms/step - loss: 0.0898 - accuracy: 0.9675 - val_loss: 0.1303 - val_accuracy: 0.9578
Epoch 2/50
122/121 [==============================] - 34s 281ms/step - loss: 0.1028 - accuracy: 0.9639 - val_loss: 0.1774 - val_accuracy: 0.9361
Epoch 3/50
122/121 [==============================] - 34s 281ms/step - loss: 0.1017 - accuracy: 0.9624 - val_loss: 0.1265 - val_accuracy: 0.9495
Epoch 4/50
122/121 [==============================] - 34s 282ms/step - loss: 0.0881 - accuracy: 0.9660 - val_loss: 0.1269 - val_accuracy: 0.9547
Epoch 5/50
122/121 [==============================] - 36s 294ms/step - loss: 0.0972 - accuracy: 0.9611 - val_loss: 0.1468 - val_accuracy: 0.9434
Epoch 6/50
122/121 [==============================] - 34s 282ms/step - loss: 0.1005 - accuracy: 0.9637 - val_loss: 0.1213 - val_accuracy: 0.9547
Epoch 7/50
122/121 [==============================] - 35s 284ms/step - loss: 0.0929 - accuracy: 0.9662 - val_loss: 0.1288 - val_ac

In [20]:
model.save('CNN_Model_100.h5')

<h1>Train เพิ่มอีก  epochs=50<h1>

In [17]:
model = load_model('CNN_Model_100.h5')
tf.debugging.set_log_device_placement(True)
model.fit_generator(datagen.flow(X_train, y_train, batch_size=32),
                    validation_data=(X_test,y_test),
                    steps_per_epoch=len(X_train) / 32, epochs=50)


Epoch 1/50
122/121 [==============================] - 37s 300ms/step - loss: 0.0838 - accuracy: 0.9701 - val_loss: 0.0693 - val_accuracy: 0.9804
Epoch 2/50
122/121 [==============================] - 34s 277ms/step - loss: 0.0745 - accuracy: 0.9729 - val_loss: 0.0688 - val_accuracy: 0.9722
Epoch 3/50
122/121 [==============================] - 34s 277ms/step - loss: 0.0815 - accuracy: 0.9704 - val_loss: 0.0752 - val_accuracy: 0.9743
Epoch 4/50
122/121 [==============================] - 34s 280ms/step - loss: 0.0745 - accuracy: 0.9722 - val_loss: 0.0760 - val_accuracy: 0.9691
Epoch 5/50
122/121 [==============================] - 34s 276ms/step - loss: 0.0722 - accuracy: 0.9735 - val_loss: 0.0698 - val_accuracy: 0.9732
Epoch 6/50
122/121 [==============================] - 34s 279ms/step - loss: 0.0808 - accuracy: 0.9724 - val_loss: 0.0714 - val_accuracy: 0.9691
Epoch 7/50
122/121 [==============================] - 34s 276ms/step - loss: 0.0878 - accuracy: 0.9693 - val_loss: 0.0595 - val_a

In [18]:
model.save('CNN_Model_150.h5')

200

In [20]:
model = load_model('CNN_Model_150.h5')
tf.debugging.set_log_device_placement(True)
model.fit_generator(datagen.flow(X_train, y_train, batch_size=32),
                    validation_data=(X_test,y_test),
                    steps_per_epoch=len(X_train) / 32, epochs=50)

Epoch 1/50
122/121 [==============================] - 46s 378ms/step - loss: 0.0616 - accuracy: 0.9786 - val_loss: 0.0449 - val_accuracy: 0.9846
Epoch 2/50
122/121 [==============================] - 40s 328ms/step - loss: 0.0680 - accuracy: 0.9763 - val_loss: 0.0400 - val_accuracy: 0.9835
Epoch 3/50
122/121 [==============================] - 41s 336ms/step - loss: 0.0674 - accuracy: 0.9724 - val_loss: 0.0577 - val_accuracy: 0.9804
Epoch 4/50
122/121 [==============================] - 41s 333ms/step - loss: 0.0564 - accuracy: 0.9812 - val_loss: 0.0424 - val_accuracy: 0.9825
Epoch 5/50
122/121 [==============================] - 41s 337ms/step - loss: 0.0579 - accuracy: 0.9784 - val_loss: 0.0670 - val_accuracy: 0.9794
Epoch 6/50
122/121 [==============================] - 42s 347ms/step - loss: 0.0498 - accuracy: 0.9848 - val_loss: 0.0639 - val_accuracy: 0.9753
Epoch 7/50
122/121 [==============================] - 44s 359ms/step - loss: 0.0557 - accuracy: 0.9802 - val_loss: 0.0598 - val_ac

In [21]:
model.save('CNN_Model_200.h5')

<h1>ทดสอบโมเดล<h1>

In [24]:
test = load_images_from_folder_test()

In [25]:
X_testt = np.array([i[0] for i in test]).reshape(-1,224,224,3)/255.

In [26]:
y_testt = np.array([i[1] for i in test])

<h2>โมดล50รอบ<h2>

In [25]:
model = load_model('CNN_Model.h5')

In [27]:
rounded_labels=np.argmax(y_testt, axis=1)
rounded_labels[1]

1

In [29]:
model.evaluate(X_testt, y_testt, verbose=0)

[0.16622286983443507, 0.9402515888214111]

In [30]:
prediction = model.predict_classes(X_testt)
print(classification_report(rounded_labels, prediction))

              precision    recall  f1-score   support

           0       0.96      0.93      0.94       338
           1       0.92      0.95      0.94       298

    accuracy                           0.94       636
   macro avg       0.94      0.94      0.94       636
weighted avg       0.94      0.94      0.94       636



In [31]:
prediction = model.predict_classes(X_testt)
confusion_matrix(rounded_labels, prediction)

array([[314,  24],
       [ 14, 284]], dtype=int64)

<h2>โมดล100รอบ<h2>

In [32]:
model = load_model('CNN_Model_100.h5')

In [33]:
model.evaluate(X_testt, y_testt, verbose=0)

[0.2019020823656388, 0.9292452931404114]

In [34]:
prediction = model.predict_classes(X_testt)
print(classification_report(rounded_labels, prediction))

              precision    recall  f1-score   support

           0       0.98      0.88      0.93       338
           1       0.88      0.98      0.93       298

    accuracy                           0.93       636
   macro avg       0.93      0.93      0.93       636
weighted avg       0.93      0.93      0.93       636



In [35]:
prediction = model.predict_classes(X_testt)
confusion_matrix(rounded_labels, prediction)

array([[299,  39],
       [  6, 292]], dtype=int64)

<h2>โมดล150รอบ<h2>

In [5]:
model = load_model('CNN_Model_150.h5')

In [24]:
model.evaluate(X_testt, y_testt, verbose=0)

[0.2794041603381904, 0.9292452931404114]

In [27]:
prediction = model.predict_classes(X_testt)
print(classification_report(rounded_labels, prediction))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       338
           1       0.89      0.97      0.93       298

    accuracy                           0.93       636
   macro avg       0.93      0.93      0.93       636
weighted avg       0.93      0.93      0.93       636



In [28]:
prediction = model.predict_classes(X_testt)
confusion_matrix(rounded_labels, prediction)

array([[302,  36],
       [  9, 289]], dtype=int64)

In [22]:
model = load_model('CNN_Model_200.h5')

In [28]:
model.evaluate(X_testt, y_testt, verbose=0)

[0.20499521065737653, 0.9433962106704712]

In [29]:
prediction = model.predict_classes(X_testt)
print(classification_report(rounded_labels, prediction))

              precision    recall  f1-score   support

           0       0.98      0.91      0.94       338
           1       0.91      0.98      0.94       298

    accuracy                           0.94       636
   macro avg       0.94      0.95      0.94       636
weighted avg       0.95      0.94      0.94       636



In [30]:
prediction = model.predict_classes(X_testt)
confusion_matrix(rounded_labels, prediction)

array([[308,  30],
       [  6, 292]], dtype=int64)