In [1]:
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score, f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import warnings

In [4]:
df = pd.read_csv('dataset/Data/totalwithmaininfo.csv',sep=',')
df = df.drop(df.columns[0],axis=1)

In [5]:
df

Y       EAR       MAR  Circularity       MOE     EAR_N     MAR_N  \
0      0  0.315900  0.986514     0.450053  3.122874 -0.871732 -0.022238   
1      0  0.320060  0.967440     0.497489  3.022686 -0.219925 -0.988696   
2      0  0.328431  1.006906     0.518270  3.065808  1.091657  1.010933   
3      0  0.351223  1.102950     0.536187  3.140313  4.662748  5.877299   
4      0  0.337345  1.094224     0.504254  3.243631  2.488390  5.435149   
...   ..       ...       ...          ...       ...       ...       ...   
9595  10  0.275401  1.182630     0.414005  4.294205 -1.117401  4.190975   
9596  10  0.204631  1.189241     0.291487  5.811628 -2.777285  4.387865   
9597  10  0.290996  1.110189     0.398633  3.815133 -0.751634  2.033375   
9598  10  0.301910  1.143009     0.420446  3.785924 -0.495647  3.010903   
9599  10  0.250010  1.143407     0.439890  4.573453 -1.712957  3.022742   

      Circularity_N     MOE_N  
0         -1.102540  1.043034  
1          0.254111 -0.950539  
2          0.848429 -0.092496  
3          1.360857  1.390040  
4          0.447582  3.445910  
...             ...       ...  
9595      -0.958109  2.483317  
9596      -3.855693  6.131075  
9597      -1.321658  1.331666  
9598      -0.805777  1.261450  
9599      -0.345922  3.154605  

[9600 rows x 9 columns]

In [6]:
df = df[df.Y != 5]

In [7]:
train_percentage = 7/8
train_index = int(len(df)*train_percentage)
test_index = len(df)-train_index

In [8]:
df_train = df[:train_index]
df_test = df[-test_index:]

In [9]:
df_test

Y       EAR       MAR  Circularity       MOE     EAR_N     MAR_N  \
8400   0  0.346804  1.022771     0.479602  2.949136  0.557304 -0.570294   
8401   0  0.273821  1.022298     0.405698  3.733454 -1.154471 -0.584378   
8402   0  0.348503  1.080686     0.478248  3.100938  0.597167  1.154672   
8403   0  0.282846  1.051722     0.435547  3.718361 -0.942799  0.292007   
8404   0  0.363169  1.057844     0.528093  2.912813  0.941154  0.474336   
...   ..       ...       ...          ...       ...       ...       ...   
9595  10  0.275401  1.182630     0.414005  4.294205 -1.117401  4.190975   
9596  10  0.204631  1.189241     0.291487  5.811628 -2.777285  4.387865   
9597  10  0.290996  1.110189     0.398633  3.815133 -0.751634  2.033375   
9598  10  0.301910  1.143009     0.420446  3.785924 -0.495647  3.010903   
9599  10  0.250010  1.143407     0.439890  4.573453 -1.712957  3.022742   

      Circularity_N     MOE_N  
8400       0.593287 -0.750118  
8401      -1.154553  1.135317  
8402       0.561266 -0.385199  
8403      -0.448633  1.099036  
8404       1.740125 -0.837434  
...             ...       ...  
9595      -0.958109  2.483317  
9596      -3.855693  6.131075  
9597      -1.321658  1.331666  
9598      -0.805777  1.261450  
9599      -0.345922  3.154605  

[800 rows x 9 columns]

In [10]:
df_train

Y       EAR       MAR  Circularity       MOE      EAR_N     MAR_N  \
0      0  0.315900  0.986514     0.450053  3.122874  -0.871732 -0.022238   
1      0  0.320060  0.967440     0.497489  3.022686  -0.219925 -0.988696   
2      0  0.328431  1.006906     0.518270  3.065808   1.091657  1.010933   
3      0  0.351223  1.102950     0.536187  3.140313   4.662748  5.877299   
4      0  0.337345  1.094224     0.504254  3.243631   2.488390  5.435149   
...   ..       ...       ...          ...       ...        ...       ...   
8395  10  0.174018  1.004202     0.323922  5.770694 -12.219281  7.158256   
8396  10  0.208323  1.012277     0.429090  4.859160  -6.492919  7.440192   
8397  10  0.225565  1.036113     0.425152  4.593413  -3.614978  8.272402   
8398  10  0.225565  1.017720     0.425152  4.511875  -3.614978  7.630239   
8399  10  0.192675  1.004988     0.402767  5.215977  -9.105004  7.185674   

      Circularity_N      MOE_N  
0         -1.102540   1.043034  
1          0.254111  -0.950539  
2          0.848429  -0.092496  
3          1.360857   1.390040  
4          0.447582   3.445910  
...             ...        ...  
8395      -3.565366  18.836416  
8396       1.673815  12.068244  
8397       1.477608  10.095060  
8398       1.477608   9.489633  
8399       0.362494  14.717625  

[5600 rows x 9 columns]

In [11]:
X_test = df_test.drop(["Y"],axis=1)
y_test = df_test["Y"]

In [12]:
X_train = df_train.drop('Y',axis=1)
y_train = df_train['Y']

In [ ]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [13]:
def average(y_pred):
    for i in range(len(y_pred)):
        if i % 612 == 0 or (i+1) % 612 == 0:
            y_pred[i] = 0
            pass
        else:
            if i+1 == range(len(y_pred)):
                average = float(y_pred[i-1] +  y_pred[i])/2
                print("Fuck")
            else:
                average = float(y_pred[i-1] +  y_pred[i] + y_pred[i+1])/3
                                
            if average >= 0.5:
                y_pred[i] = 1
            else:
                y_pred[i] = 0
    return y_pred

In [14]:
def average(y_pred):
    for i in range(len(y_pred)):
        if i % 400 == 0 or (i+1) % 400 == 0:
            y_pred[i] = 0
            pass
        else: 
            average = float(y_pred[i-1] +  y_pred[i] + y_pred[i+1])/3
            if average >= 0.5:
                y_pred[i] = 1
            else:
                y_pred[i] = 0
    return y_pred

In [25]:
#old
clf = LogisticRegression().fit(X_train, y_train)
y_pred_1 = clf.predict(X_test)
#y_pred_1 = average(y_pred_1)
y_score_1 = clf.predict_proba(X_test)[:,1]
acc1 = accuracy_score(y_test, y_pred_1)
f1_score_1 = metrics.f1_score(y_test, y_pred_1,average='macro')
print([acc1,f1_score_1])
print(confusion_matrix(y_test, y_pred_1))

[0.81125, 0.810752930744659]
[[345  55]
 [ 96 304]]


In [26]:
y_pred_1

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0, 10,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,
        0,  0, 10,  0, 10, 10,  0,  0,  0,  0,  0,  0, 10,  0,  0, 10,  0,
        0,  0,  0,  0, 10,  0,  0,  0, 10, 10, 10, 10, 10,  0,  0,  0, 10,
       10,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [27]:
acc3_list = []
f1_score3_list = []
roc_3_list = []
from sklearn.neighbors import KNeighborsClassifier
for i in range(1,30):
    neigh = KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train, y_train) 
    pred_KN = neigh.predict(X_test)
    #pred_KN = average(pred_KN)
    y_score_3 = neigh.predict_proba(X_test)[:,1]
    acc3_list.append(accuracy_score(y_test, pred_KN))
    f1_score3_list.append(metrics.f1_score(y_test, pred_KN,average='micro'))
    #roc_3_list.append(metrics.roc_auc_score(y_test, y_score_3,multi_class='ovr'))

In [28]:
pred_KN

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,
        0,  0, 10,  0,  0,  0,  0,  0,  0, 10,  0, 10, 10,  0,  0,  0,  0,
        0, 10,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10, 10,  0, 10, 10,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,
        0,  0, 10,  0,  0,  0,  0,  0,  0,  0, 10,  0, 10,  0,  0, 10,  0,
        0,  0,  0,  0, 10,  0, 10, 10,  0, 10,  0,  0,  0, 10,  0,  0, 10,
        0,  0, 10, 10, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10,
        0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10,  0,  0,  0,  0,  0,
        0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [29]:
acc3_list

[0.6725,
 0.66875,
 0.68,
 0.65375,
 0.6625,
 0.66,
 0.6675,
 0.6725,
 0.68125,
 0.6775,
 0.67625,
 0.675,
 0.6725,
 0.66875,
 0.6675,
 0.6675,
 0.6675,
 0.67,
 0.66875,
 0.67,
 0.66125,
 0.66625,
 0.66375,
 0.6675,
 0.66875,
 0.67125,
 0.6725,
 0.67,
 0.67125]

In [30]:
acc3_list.index(max(acc3_list))+1

9

In [31]:
#KNN
neigh = KNeighborsClassifier(n_neighbors=acc3_list.index(max(acc3_list))+1)
neigh.fit(X_train, y_train) 
pred_KN = neigh.predict(X_test)
#pred_KN = average(pred_KN)
y_score_3 = neigh.predict_proba(X_test)[:,1]
acc3 = accuracy_score(y_test, pred_KN)
f1_score_3 = metrics.f1_score(y_test, pred_KN,average='micro')
#roc_3 = metrics.roc_auc_score(y_test, y_score_3)
print([acc3,f1_score_3])
print(confusion_matrix(y_test, pred_KN))

[0.68125, 0.68125]
[[329  71]
 [184 216]]


In [32]:
f1_score_3

0.68125

In [33]:
#MLP
from sklearn.neural_network import MLPClassifier

F1_score_4_list = []
acc4_list = []
roc_4_list = []
mlp = []

hidden_units = [10,20,30,40,50,60,70]
optimizer = ['sgd','adam','lbfgs']
activation = ['logistic','tanh','relu']
for j in activation:
    for i in optimizer:
        for k in hidden_units:
            clf_MLP = MLPClassifier(hidden_layer_sizes= k, activation =  j, solver= i)
            clf_MLP.fit(X_train, y_train)
            pred_MLP = clf_MLP.predict(X_test)
            #pred_MLP = average(pred_MLP)
            y_score_4 = clf_MLP.predict_proba(X_test)[:,1]
            acc4_list.append(accuracy_score(y_test,pred_MLP))
            #roc_4_list.append(metrics.roc_auc_score(y_test, y_score_4))
            F1_score_4_list.append(metrics.f1_score(y_test, pred_MLP,average='micro'))
            mlp.append([j,i,k])

C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, Conv

C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.

C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

In [34]:
print("Best Accuracy: ", max(acc4_list))
min_index = acc4_list.index(max(acc4_list))
print("Best Combination:", mlp[min_index])

Best Accuracy:  0.805
Best Combination: ['tanh', 'sgd', 70]


In [35]:
clf_MLP = MLPClassifier(hidden_layer_sizes= mlp[min_index][2], activation =  mlp[min_index][0], solver= mlp[min_index][1])
clf_MLP.fit(X_train, y_train)
pred_MLP = clf_MLP.predict(X_test)
y_score_4 = clf_MLP.predict_proba(X_test)[:,1]
acc4 = accuracy_score(y_test,pred_MLP)
f1_score_4 = metrics.f1_score(y_test, pred_MLP,average='micro')
print([acc4,f1_score_4])
print(confusion_matrix(y_test, pred_MLP))

[0.81, 0.81]
[[346  54]
 [ 98 302]]


C:\Users\nataw\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [43]:
from sklearn.metrics import accuracy_score, classification_report
target_names = ['alert', 'sleepy']

print(classification_report(y_test, pred_MLP, target_names=target_names))

              precision    recall  f1-score   support

       alert       0.78      0.86      0.82       400
      sleepy       0.85      0.76      0.80       400

    accuracy                           0.81       800
   macro avg       0.81      0.81      0.81       800
weighted avg       0.81      0.81      0.81       800



In [36]:
clf_NB = GaussianNB()
clf_NB.fit(X_train, y_train)
pred_NB = clf_NB.predict(X_test)
#pred_NB = average(pred_NB)
y_score_2 = clf_NB.predict_proba(X_test)[:,1]
acc2 = accuracy_score(y_test, pred_NB)
f1_score_2 = metrics.f1_score(y_test, pred_NB,average='micro')
#roc_2 = metrics.roc_auc_score(y_test, y_score_2)
print([acc2,f1_score_2])
print(confusion_matrix(y_test, pred_NB))

[0.74, 0.74]
[[339  61]
 [147 253]]


In [37]:
from sklearn.tree import DecisionTreeClassifier
acc5=[]
max_depth = []
for i in [2,3,4,5,6,7,8,9,10]:
    clf_DT = DecisionTreeClassifier(random_state=0, max_depth = i)
    clf_DT.fit(X_train, y_train)
    pred_DT = clf_DT.predict(X_test)
    #pred_DT = average(pred_DT)
    acc5.append(accuracy_score(pred_DT, y_test))
    max_depth.append(i)
print (max(acc5))

0.78


In [21]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
parameters = { 'C':np.arange(1,15,0.5)}
svc = svm.SVC()
SVM=GridSearchCV(svc, parameters)
SVM.fit(X_train,y_train)
SVM.best_estimator_

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [24]:
SVM.score(X_test, y_test)

0.74875

In [1]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

C:\Users\nataw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\nataw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\nataw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\nataw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

Num GPUs Available:  1
